### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by chris-tran-16** [Diviyan-Kalainathan/CausalDiscoveryToolbox#24] opened 2019-06-18 15:03 UTC
When I'm trying to run some examples with different parameters, I get this error:

> FileNotFoundError: File b'/tmp/cdt_CAMbc4bbf1c-b80b-4e8b-9184-23ba73222cce/result.csv' does not exist

Here is the snippet of code I'm trying to run

> import networkx as nx
> from cdt.causality.graph import CAM
> from cdt.data import load_dataset
> data, graph = load_dataset("sachs")
> obj = CAM(selmethod='gam')
> output = obj.predict(data)

**Comment by Diviyan-Kalainathan** [comment] 2019-06-18 15:11
Hi Chris, 
Thanks for the feedback, it seems all variable selection methods but 'gamboost' are not working,
I will further investigate this

**Comment by Diviyan-Kalainathan** [comment] 2019-06-25 09:18
Hi again Chris,
Sorry for the delay,

Actually I should find a way to traceback the error from the R process. This FileNotFoundError occurs when the R subprocess errors. After investigation, the error comes down to the variable selection methods, which are not fit for small graphs: the CAM R package reports the same issue. 
Therefore, For small graphs you should consider setting ``variablesel=False``, which is computationally heavier, but unnoticeable on small graphs.

Since this is a bug on CAM and on its usage, I will be closing this issue, but feel free to discuss.

Best,
Diviyan

**Closed by Diviyan-Kalainathan** 2019-06-25 09:18 UTC
Labels: bug

**Comment by sixteenyear** [comment] 2020-08-04 12:11
Hi  Diviyan,
Is this error resolved? I also encountered the same error.

![image](https://user-images.githubusercontent.com/52397681/89292062-46380d00-d68e-11ea-887c-4200fec4a93f.png)

**Comment by Diviyan-Kalainathan** [comment] 2020-08-04 12:55
Hello, this error actually mirrors an error in the R process ; could you share an code snippet that reproduces the error ?

**Comment by sixteenyear** [comment] 2020-08-05 01:02
import pandas as pd
import cdt
from cdt.causality.graph import GES,GIES,CCDr,LiNGAM,PC,MMPC,   IAMB,Fast_IAMB,Inter_IAMB,GS,CGNN,SAM,SAMv1,  CAM
from cdt.data import load_dataset
import networkx as nx
import matplotlib.pyplot as plt

print("SAM")
# data, graph = load_dataset("sachs")
data = pd.read_csv('./data/server_sample/1_example.csv')
data.drop(['Unnamed: 0'],axis=1,inplace = True)
data=data.astype(float)
obj = SAM()
output = obj.predict(data) #No graph provided as an argument
# output = obj.predict(data, nx.Graph(graph)) #With an undirected graph
# output = obj.predict(data, graph)  #With a directed graph
print('edge is ', output.edges())
data = pd.DataFrame({"edge": output.edges()})
data.to_csv("./data/server_sample/1/edge_SAM_alg.csv")
print('edge num', output.number_of_edges())
nx.draw_networkx(output, font_size=8)
plt.show()

Data  as follows
![image](https://user-images.githubusercontent.com/52397681/89360206-41a93e00-d6fa-11ea-929a-c1d06bbcffee.png)

**Comment by sixteenyear** [comment] 2020-08-05 07:41
hello, I have multiple data sets, with nodes ranging from 30 to 150, and data volumes ranging from 10,000 to 500,000.

For some algorithms in CDT, such as IAMB,GS,CGNN, etc. on a certain data set, the algorithm has been running for a long time and has not finished yet. May I ask if the running time can be estimated? In this way, I can roughly know when the algorithm can finish running.

**Comment by Diviyan-Kalainathan** [comment] 2020-08-05 09:17
Hi, I'm not able to reproduce your error... can you share your data ? 

For having an estimation, there is no direct way of having it. One way could be to enable verbosity for the models  by setting `verbose=True`

Please note that CGNN scales quadratically on the number of nodes and number of data points. I think that using CGNN might be unfit for your case as the computational time might be too high.

Best regards, 
Diviyan

**Comment by sixteenyear** [comment] 2020-08-05 11:43
Data as follows
[example.zip](https://github.com/FenTechSolutions/CausalDiscoveryToolbox/files/5028058/example.zip)

**Comment by Diviyan-Kalainathan** [comment] 2020-08-12 08:33
Could you try again with the latest version on the `dev` branch ? I recently fixed a bug on CAM on windows platforms
Best,
Diviyan
