### ISSUE TITLE
CGNN Module : unexpected argument (nb_runs,nb_max_runs, etc)

### ISSUE THREAD

**Issue by conrev** [Diviyan-Kalainathan/CausalDiscoveryToolbox#10] opened 2018-09-05 09:56 UTC
When i tried to run the example, this line
``Cgnn.predict(data, graph=ugraph, nb_runs=12, nb_max_runs=20, train_epochs=1500, test_epochs=1000)`` 
Produces an unexpected argument error, is there any changes in the CGNN module that causes this? i tried investigating the module but i cant seem to figure out why this happens. Is this reproducible in your machine?

**Comment by Diviyan-Kalainathan** [comment] 2018-09-05 09:59
Hi,
Whoops, yes I forgot to update the example ; the argument nb_max_runs is deprecated. Removing it should work
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment] 2018-09-11 15:36
Feel free to close the issue if the problem is solved !

**Comment by conrev** [comment] 2018-09-19 01:28
Thank you for the quick response!

**Closed** 2018-09-19 01:29 UTC
