### ISSUE TITLE
NCC.py

### ISSUE THREAD

**Issue by vipulbjj** [Diviyan-Kalainathan/CausalDiscoveryToolbox#12] opened 2018-11-03 21:52 UTC
It is written in the code that it outputs 1 or -1 but sigmoid has been used which outputs between 0 and 1. So data with which type of labels is required? Please solve this issue.

**Comment by Diviyan-Kalainathan** [comment] 2018-11-06 13:11
Thank you for the feedback, 

I noticed that even then, this version of NCC is bugged. I will recode it. 
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment] 2018-11-12 15:01
Hi,
It should be fixed by now. The targets are -1,1 like other algorithms. Although I used a dirty trick of `y = y/2 + .5`...

Best,
Diviyan

**Comment by vipulbjj** [comment] 2018-11-14 01:14
@Diviyan-Kalainathan I tried training this a number of times with different amounts of data. But I'm getting the same output for every input. After trying to debug I realised that it's output before the sigmoid layer is very close to 0 and due to the slope being very low there, the differences before the sigmoid layer(small) diminish. Can you please check it? Maybe the number of hidden layers in the model is less than what is required for a sizeable data.

**Comment by Diviyan-Kalainathan** [comment] 2018-11-14 08:18
Very strange... have you updated your package ? 
Which kind of data are you using to train the model ? (remember to feed labels -1, +1) (If it's a public dataset, I'll be glad to take a look)
I am not able to reproduce this, in my case the model trains properly (on a simple dataset though)
There is a hyperparameter that you can modify to change the number of hidden units, but not for the number of layers ; try increasing the number of hidden units for now.

Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment] 2019-01-08 09:49
Closing for inactivity. Feel free to reopen it if not solved.

**Closed by Diviyan-Kalainathan** 2019-01-08 09:49 UTC
Labels: bug
